### ISSUE TITLE
Create Kapsch CMCC publisher deployment

### ISSUE THREAD

**Issue by jeffgrunewald** [UrbanOS-Examples/charts#1]
As the program, I need to receive data from the CV environment, so that I can meet my KPIs

Create the deployment that will add the Kapsch control unit data publisher to the project's K8s cluster so the data can be consumed by the data pipeline

ACs:
- Create a columbus-specific deploy repo or deployment manifest (under common or similar)
- Kapsch application should be deployed to its own namespace with a single-pod deployment and a service
- Environment variables for the kapsch deployment should be pulled from the notes in the closed GitHub issue github.com/smartcolumbusos/migration/issues/247

Amigos: 
@jeffgrunewald

**Comment by bbrewer-forge** [comment]
arguments needed to start the container:
-e cmccdatapublisher.udpPublishPort=_PORT_
-e cmccdatapublisher.udpPublishHost=_ADDRESS_
-e logging_level_net_kapsch=TRACE (for debugging _only_)

**Comment by jeffgrunewald** [comment]
the marysville deployment has moved off the Kapsch "default" prod instance so now it requires additional arguments when starting the container to connect to. The following must also be supplied:
```
-e cmccdatapublisher.commServicesHost=ohiort33.etranssystems.com
-e cmccdatapublisher.commServicesRsu=m14_rsu
-e cmccdatapublisher.commServicesPassowrd="password stored in AWS secrets manager ALM acct"
```
!NOTE! the "typo" in the above environment variable arg (passowrd) is a deliberate misspelling, as the Kapsch-provided image has the environment variable misspelled in its config. Please contact Kapsch if and/when this is patched in a subsequent upgrade of the publisher image to ensure we are able to connect.
